//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kombatant.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kombatant.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [PVP]Target Mounted Enemy First 的本地化字符串。
        /// </summary>
        public static string _PVP_Target_Mounted_Enemy_First {
            get {
                return ResourceManager.GetString("[PVP]Target Mounted Enemy First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [PVP]Target Pc Or Npc First 的本地化字符串。
        /// </summary>
        public static string _PVP_Target_PC_First {
            get {
                return ResourceManager.GetString("[PVP]Target PC First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [PVP]Target WarMachina First 的本地化字符串。
        /// </summary>
        public static string _PVP_Target_WarMachina_First {
            get {
                return ResourceManager.GetString("[PVP]Target WarMachina First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Vote Mvp 的本地化字符串。
        /// </summary>
        public static string Auto_Vote_Mvp {
            get {
                return ResourceManager.GetString("Auto Vote Mvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Distance 的本地化字符串。
        /// </summary>
        public static string Follow_Distance {
            get {
                return ResourceManager.GetString("Follow Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Mode 的本地化字符串。
        /// </summary>
        public static string Follow_Mode {
            get {
                return ResourceManager.GetString("Follow Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Face Target DISABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AutoFaceTargetOff {
            get {
                return ResourceManager.GetString("Msg_AutoFaceTargetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Face Target ENABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AutoFaceTargetOn {
            get {
                return ResourceManager.GetString("Msg_AutoFaceTargetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autonomous Mode DISABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AutonomousOff {
            get {
                return ResourceManager.GetString("Msg_AutonomousOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autonomous Mode ENABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AutonomousOn {
            get {
                return ResourceManager.GetString("Msg_AutonomousOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target is part of FATE &quot;{0}&quot;, syncing level... 的本地化字符串。
        /// </summary>
        public static string Msg_AutoSyncFate {
            get {
                return ResourceManager.GetString("Msg_AutoSyncFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Targeting DISABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AutoTargetOff {
            get {
                return ResourceManager.GetString("Msg_AutoTargetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Targeting ENABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AutoTargetOn {
            get {
                return ResourceManager.GetString("Msg_AutoTargetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fight is over.
        ///Avoidance will RESUME 的本地化字符串。
        /// </summary>
        public static string Msg_AvoidanceDisabledOnBossEnd {
            get {
                return ResourceManager.GetString("Msg_AvoidanceDisabledOnBossEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fighting {0}!
        ///Avoidance will PAUSE 的本地化字符串。
        /// </summary>
        public static string Msg_AvoidanceDisabledOnBossStart {
            get {
                return ResourceManager.GetString("Msg_AvoidanceDisabledOnBossStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avoidance finished, stopping movement... 的本地化字符串。
        /// </summary>
        public static string Msg_AvoidanceFinished {
            get {
                return ResourceManager.GetString("Msg_AvoidanceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avoidance DISABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AvoidanceOff {
            get {
                return ResourceManager.GetString("Msg_AvoidanceOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avoidance ENABLED 的本地化字符串。
        /// </summary>
        public static string Msg_AvoidanceOn {
            get {
                return ResourceManager.GetString("Msg_AvoidanceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirming Duty... 的本地化字符串。
        /// </summary>
        public static string Msg_DutyConfirm {
            get {
                return ResourceManager.GetString("Msg_DutyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Let the revels begin! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche0 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rise, rise to the occasion! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche1 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 Gil says someone is not going to accept... 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche2 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 So excited! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche3 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And so are we! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche4 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 REJOICE! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche5 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initiate soul extraction! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche6 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behold, fury given form! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche7 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more games! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche8 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mechanics are for cars! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyPsyche9 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duty is ready! 的本地化字符串。
        /// </summary>
        public static string Msg_DutyReady {
            get {
                return ResourceManager.GetString("Msg_DutyReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following DISABLED 的本地化字符串。
        /// </summary>
        public static string Msg_FollowingOff {
            get {
                return ResourceManager.GetString("Msg_FollowingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following ENABLED 的本地化字符串。
        /// </summary>
        public static string Msg_FollowingOn {
            get {
                return ResourceManager.GetString("Msg_FollowingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fight is over. Avoidance will RESUME. 的本地化字符串。
        /// </summary>
        public static string Msg_Log_AvoidanceDisabledOnBossEnd {
            get {
                return ResourceManager.GetString("Msg_Log_AvoidanceDisabledOnBossEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fighting known boss. Avoidance will temporarily PAUSE. 的本地化字符串。
        /// </summary>
        public static string Msg_Log_AvoidanceDisabledOnBossStart {
            get {
                return ResourceManager.GetString("Msg_Log_AvoidanceDisabledOnBossStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}!
        ///Turn away before the cast completes! 的本地化字符串。
        /// </summary>
        public static string Msg_MechanicWarning_Gaze {
            get {
                return ResourceManager.GetString("Msg_MechanicWarning_Gaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}!
        ///Stop moving or attacking! 的本地化字符串。
        /// </summary>
        public static string Msg_MechanicWarning_StandStill {
            get {
                return ResourceManager.GetString("Msg_MechanicWarning_StandStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}!
        ///Stop all activities before the timer reaches zero! 的本地化字符串。
        /// </summary>
        public static string Msg_MechanicWarning_StandStillOnZero {
            get {
                return ResourceManager.GetString("Msg_MechanicWarning_StandStillOnZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New target selected: {0} {1} 的本地化字符串。
        /// </summary>
        public static string Msg_NewTargetSelected {
            get {
                return ResourceManager.GetString("Msg_NewTargetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running at a tickrate other than 30 TPS!
        ///See RebornBuddy log for more details. 的本地化字符串。
        /// </summary>
        public static string Msg_Not30Tps {
            get {
                return ResourceManager.GetString("Msg_Not30Tps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///*************************** [ KOMBATANT WARNING! ] ***************************
        ///*                                                                            *
        ///* Operating at a tickrate other than 30! Botbase might not work as expected! *
        ///*    For optimal botbase performance, please set your TPS to exactly 30.     *
        ///*                                                                            *
        ///******************************************************************************
        ///         的本地化字符串。
        /// </summary>
        public static string Msg_Not30Tps_Log {
            get {
                return ResourceManager.GetString("Msg_Not30Tps_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kombatant PAUSED 的本地化字符串。
        /// </summary>
        public static string Msg_Paused {
            get {
                return ResourceManager.GetString("Msg_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling {0} 的本地化字符串。
        /// </summary>
        public static string Msg_PulseFlagDisabled {
            get {
                return ResourceManager.GetString("Msg_PulseFlagDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling {0} 的本地化字符串。
        /// </summary>
        public static string Msg_PulseFlagEnabled {
            get {
                return ResourceManager.GetString("Msg_PulseFlagEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings have been reloaded. 的本地化字符串。
        /// </summary>
        public static string Msg_ReloadedSettings {
            get {
                return ResourceManager.GetString("Msg_ReloadedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kombatant RESUMED 的本地化字符串。
        /// </summary>
        public static string Msg_Unpaused {
            get {
                return ResourceManager.GetString("Msg_Unpaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kombatant 的本地化字符串。
        /// </summary>
        public static string Name_Kombatant {
            get {
                return ResourceManager.GetString("Name_Kombatant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Target Tanked Enemy 的本地化字符串。
        /// </summary>
        public static string Only_Target_Tanked_Enemy {
            get {
                return ResourceManager.GetString("Only Target Tanked Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Following On Bosses 的本地化字符串。
        /// </summary>
        public static string Pause_Following_On_Bosses {
            get {
                return ResourceManager.GetString("Pause Following On Bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dungeon Only 的本地化字符串。
        /// </summary>
        public static string Sprints_In_Dungeon_Only {
            get {
                return ResourceManager.GetString("Sprints In Dungeon Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Name 的本地化字符串。
        /// </summary>
        public static string Target_Name {
            get {
                return ResourceManager.GetString("Target Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Commence Duty 的本地化字符串。
        /// </summary>
        public static string UI_AutoAcceptDutyFinder {
            get {
                return ResourceManager.GetString("UI_AutoAcceptDutyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Accept Quests 的本地化字符串。
        /// </summary>
        public static string UI_AutoAcceptQuests {
            get {
                return ResourceManager.GetString("UI_AutoAcceptQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Accept Revive 的本地化字符串。
        /// </summary>
        public static string UI_AutoAcceptRevive {
            get {
                return ResourceManager.GetString("UI_AutoAcceptRevive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Advance Dialogue 的本地化字符串。
        /// </summary>
        public static string UI_AutoAdvanceDialogue {
            get {
                return ResourceManager.GetString("UI_AutoAdvanceDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Deselect 的本地化字符串。
        /// </summary>
        public static string UI_AutoDeselect {
            get {
                return ResourceManager.GetString("UI_AutoDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Emote 的本地化字符串。
        /// </summary>
        public static string UI_AutoEmote {
            get {
                return ResourceManager.GetString("UI_AutoEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto End ACT Encounters 的本地化字符串。
        /// </summary>
        public static string UI_AutoEndActEncounters {
            get {
                return ResourceManager.GetString("UI_AutoEndActEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Face Target 的本地化字符串。
        /// </summary>
        public static string UI_AutoFaceTarget {
            get {
                return ResourceManager.GetString("UI_AutoFaceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Handover 的本地化字符串。
        /// </summary>
        public static string UI_AutoHandover {
            get {
                return ResourceManager.GetString("UI_AutoHandover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Leave Duty 的本地化字符串。
        /// </summary>
        public static string UI_AutoLeaveDuty {
            get {
                return ResourceManager.GetString("UI_AutoLeaveDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Register Duty 的本地化字符串。
        /// </summary>
        public static string UI_AutoRegisterDuty {
            get {
                return ResourceManager.GetString("UI_AutoRegisterDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Select Yes 的本地化字符串。
        /// </summary>
        public static string UI_AutoSelectYes {
            get {
                return ResourceManager.GetString("UI_AutoSelectYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Skip Cutscenes 的本地化字符串。
        /// </summary>
        public static string UI_AutoSkipCutscenes {
            get {
                return ResourceManager.GetString("UI_AutoSkipCutscenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Sprint 的本地化字符串。
        /// </summary>
        public static string UI_AutoSprint {
            get {
                return ResourceManager.GetString("UI_AutoSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Sync to FATE 的本地化字符串。
        /// </summary>
        public static string UI_AutoSyncFate {
            get {
                return ResourceManager.GetString("UI_AutoSyncFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Target 的本地化字符串。
        /// </summary>
        public static string UI_AutoTarget {
            get {
                return ResourceManager.GetString("UI_AutoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Target Switching 的本地化字符串。
        /// </summary>
        public static string UI_AutoTargetSwitch {
            get {
                return ResourceManager.GetString("UI_AutoTargetSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Trade 的本地化字符串。
        /// </summary>
        public static string UI_AutoTrade {
            get {
                return ResourceManager.GetString("UI_AutoTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avoidance 的本地化字符串。
        /// </summary>
        public static string UI_Avoidance {
            get {
                return ResourceManager.GetString("UI_Avoidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bot General 的本地化字符串。
        /// </summary>
        public static string UI_BotGeneral {
            get {
                return ResourceManager.GetString("UI_BotGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bot Status 的本地化字符串。
        /// </summary>
        public static string UI_BotStatus {
            get {
                return ResourceManager.GetString("UI_BotStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check LOS 的本地化字符串。
        /// </summary>
        public static string UI_CheckLos {
            get {
                return ResourceManager.GetString("UI_CheckLos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string UI_Clear {
            get {
                return ResourceManager.GetString("UI_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combat Behavior 的本地化字符串。
        /// </summary>
        public static string UI_Combat {
            get {
                return ResourceManager.GetString("UI_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combat Buff Behavior 的本地化字符串。
        /// </summary>
        public static string UI_CombatBuff {
            get {
                return ResourceManager.GetString("UI_CombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combat Routine 的本地化字符串。
        /// </summary>
        public static string UI_CombatRoutine {
            get {
                return ResourceManager.GetString("UI_CombatRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convenience 的本地化字符串。
        /// </summary>
        public static string UI_Convenience {
            get {
                return ResourceManager.GetString("UI_Convenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose which combat routine behaviors to execute. 的本地化字符串。
        /// </summary>
        public static string UI_CRtip1 {
            get {
                return ResourceManager.GetString("UI_CRtip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usually you want all behaviors to be active. 的本地化字符串。
        /// </summary>
        public static string UI_CRtip2 {
            get {
                return ResourceManager.GetString("UI_CRtip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Death Behavior 的本地化字符串。
        /// </summary>
        public static string UI_Death {
            get {
                return ResourceManager.GetString("UI_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeathBehavior 的本地化字符串。
        /// </summary>
        public static string UI_DeathBehavior {
            get {
                return ResourceManager.GetString("UI_DeathBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duty Finder 的本地化字符串。
        /// </summary>
        public static string UI_DutyFinder {
            get {
                return ResourceManager.GetString("UI_DutyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify When Ready 的本地化字符串。
        /// </summary>
        public static string UI_DutyFinderNotify {
            get {
                return ResourceManager.GetString("UI_DutyFinderNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duty needs to Register 的本地化字符串。
        /// </summary>
        public static string UI_DutyNeedsToRegister {
            get {
                return ResourceManager.GetString("UI_DutyNeedsToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Avoidance 的本地化字符串。
        /// </summary>
        public static string UI_EnableAvoidance {
            get {
                return ResourceManager.GetString("UI_EnableAvoidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Following 的本地化字符串。
        /// </summary>
        public static string UI_EnableFollowing {
            get {
                return ResourceManager.GetString("UI_EnableFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable FATE mob filter 的本地化字符串。
        /// </summary>
        public static string UI_FateFilter {
            get {
                return ResourceManager.GetString("UI_FateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed Character 的本地化字符串。
        /// </summary>
        public static string UI_FixedCharacter {
            get {
                return ResourceManager.GetString("UI_FixedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Overlay 的本地化字符串。
        /// </summary>
        public static string UI_FocusOverlay {
            get {
                return ResourceManager.GetString("UI_FocusOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following 的本地化字符串。
        /// </summary>
        public static string UI_Following {
            get {
                return ResourceManager.GetString("UI_Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following Distance 的本地化字符串。
        /// </summary>
        public static string UI_FollowingDistance {
            get {
                return ResourceManager.GetString("UI_FollowingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friends Only 的本地化字符串。
        /// </summary>
        public static string UI_FriendsOnly {
            get {
                return ResourceManager.GetString("UI_FriendsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handover HQ 的本地化字符串。
        /// </summary>
        public static string UI_HandoverHQ {
            get {
                return ResourceManager.GetString("UI_HandoverHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string UI_Header_About {
            get {
                return ResourceManager.GetString("UI_Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CR Logic 的本地化字符串。
        /// </summary>
        public static string UI_Header_CombatRoutine {
            get {
                return ResourceManager.GetString("UI_Header_CombatRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convenience 的本地化字符串。
        /// </summary>
        public static string UI_Header_Convenience {
            get {
                return ResourceManager.GetString("UI_Header_Convenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        public static string UI_Header_Hotkeys {
            get {
                return ResourceManager.GetString("UI_Header_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movement 的本地化字符串。
        /// </summary>
        public static string UI_Header_Movement {
            get {
                return ResourceManager.GetString("UI_Header_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Targeting 的本地化字符串。
        /// </summary>
        public static string UI_Header_Targeting {
            get {
                return ResourceManager.GetString("UI_Header_Targeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heal Behavior 的本地化字符串。
        /// </summary>
        public static string UI_Heal {
            get {
                return ResourceManager.GetString("UI_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        public static string UI_Hotkeys {
            get {
                return ResourceManager.GetString("UI_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert All 的本地化字符串。
        /// </summary>
        public static string UI_InvertAll {
            get {
                return ResourceManager.GetString("UI_InvertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Autonomous Actions 的本地化字符串。
        /// </summary>
        public static string UI_IsAutonomous {
            get {
                return ResourceManager.GetString("UI_IsAutonomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        public static string UI_IsPaused {
            get {
                return ResourceManager.GetString("UI_IsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Emote Command 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_AutoEmoteCommand {
            get {
                return ResourceManager.GetString("UI_Lbl_AutoEmoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Emote Interval 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_AutoEmoteInterval {
            get {
                return ResourceManager.GetString("UI_Lbl_AutoEmoteInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Selection Strategy 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_AutoTargetingMode {
            get {
                return ResourceManager.GetString("UI_Lbl_AutoTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds To Auto Commence 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_DutyFinderWaitTime {
            get {
                return ResourceManager.GetString("UI_Lbl_DutyFinderWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Mode 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_FollowMode {
            get {
                return ResourceManager.GetString("UI_Lbl_FollowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Distance for target scan 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_TargetScanMaxDistance {
            get {
                return ResourceManager.GetString("UI_Lbl_TargetScanMaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waypoint Generation 的本地化字符串。
        /// </summary>
        public static string UI_Lbl_WaypointGenerationMode {
            get {
                return ResourceManager.GetString("UI_Lbl_WaypointGenerationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock 的本地化字符串。
        /// </summary>
        public static string UI_Lock {
            get {
                return ResourceManager.GetString("UI_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        public static string UI_Main {
            get {
                return ResourceManager.GetString("UI_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mechanic Warnings 的本地化字符串。
        /// </summary>
        public static string UI_MechanicWarnings {
            get {
                return ResourceManager.GetString("UI_MechanicWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NavGraph 的本地化字符串。
        /// </summary>
        public static string UI_NavGraph {
            get {
                return ResourceManager.GetString("UI_NavGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offmesh 的本地化字符串。
        /// </summary>
        public static string UI_Offmesh {
            get {
                return ResourceManager.GetString("UI_Offmesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party Leader 的本地化字符串。
        /// </summary>
        public static string UI_PartyLeader {
            get {
                return ResourceManager.GetString("UI_PartyLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Avoidance on Bosses 的本地化字符串。
        /// </summary>
        public static string UI_PauseAvoidanceOnBosses {
            get {
                return ResourceManager.GetString("UI_PauseAvoidanceOnBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause/Resume 的本地化字符串。
        /// </summary>
        public static string UI_PausedResume {
            get {
                return ResourceManager.GetString("UI_PausedResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Combat Buff Behavior 的本地化字符串。
        /// </summary>
        public static string UI_PreCombatBuff {
            get {
                return ResourceManager.GetString("UI_PreCombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Behavior 的本地化字符串。
        /// </summary>
        public static string UI_Pull {
            get {
                return ResourceManager.GetString("UI_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Buff Behavior 的本地化字符串。
        /// </summary>
        public static string UI_PullBuff {
            get {
                return ResourceManager.GetString("UI_PullBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Hotkeys 的本地化字符串。
        /// </summary>
        public static string UI_ReloadHotkeys {
            get {
                return ResourceManager.GetString("UI_ReloadHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rest Behavior 的本地化字符串。
        /// </summary>
        public static string UI_Rest {
            get {
                return ResourceManager.GetString("UI_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds to auto leave 的本地化字符串。
        /// </summary>
        public static string UI_SecondsToAutoLeave {
            get {
                return ResourceManager.GetString("UI_SecondsToAutoLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Combat Routine 的本地化字符串。
        /// </summary>
        public static string UI_SelectCr {
            get {
                return ResourceManager.GetString("UI_SelectCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Current 的本地化字符串。
        /// </summary>
        public static string UI_SetCurrent {
            get {
                return ResourceManager.GetString("UI_SetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kombatant Settings 的本地化字符串。
        /// </summary>
        public static string UI_SettingsWindowTitle {
            get {
                return ResourceManager.GetString("UI_SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smart Pull 的本地化字符串。
        /// </summary>
        public static string UI_SmartPull {
            get {
                return ResourceManager.GetString("UI_SmartPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Overlay 的本地化字符串。
        /// </summary>
        public static string UI_StatusOverlay {
            get {
                return ResourceManager.GetString("UI_StatusOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tank 的本地化字符串。
        /// </summary>
        public static string UI_Tank {
            get {
                return ResourceManager.GetString("UI_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Character 的本地化字符串。
        /// </summary>
        public static string UI_TargetCharacter {
            get {
                return ResourceManager.GetString("UI_TargetCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Targeting 的本地化字符串。
        /// </summary>
        public static string UI_Targeting {
            get {
                return ResourceManager.GetString("UI_Targeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Scan Interval (ms) 的本地化字符串。
        /// </summary>
        public static string UI_TargetScanFrequency {
            get {
                return ResourceManager.GetString("UI_TargetScanFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically commences a duty when it is ready. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoAcceptDutyFinder {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoAcceptDutyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically accept/complete quests. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoAcceptQuests {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoAcceptQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically skip dialogue. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoAdvanceDialogue {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoAdvanceDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emote which should automatically be kept up, i.e. &quot;/grin motion&quot; 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoEmoteCommand {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoEmoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend the emote every x seconds. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoEmoteInterval {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoEmoteInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will automatically send &quot;/echo end&quot; to the chat when no enemies are around for longer than 10 seconds. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoEndActEncounters {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoEndActEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically face the target. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoFaceTarget {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoFaceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically skip cutscenes. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoSkipCutscenes {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoSkipCutscenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically sprint when out of combat. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoSprint {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically syncs to a FATE when a FATE mob is selected as your target. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoSyncFate {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoSyncFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable automatic targeting logic. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoTarget {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables/disables automatic selection of a new target, even when the old one is still alive. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_AutoTargetSwitch {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoTargetSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the Combat behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_Combat {
            get {
                return ResourceManager.GetString("UI_Tooltip_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the CombatBuff behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_CombatBuff {
            get {
                return ResourceManager.GetString("UI_Tooltip_CombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play a random sound effect when the Duty Finder is ready. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_DutyFinderNotify {
            get {
                return ResourceManager.GetString("UI_Tooltip_DutyFinderNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow RebornBuddy to avoid telegraphed attacks. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_EnableAvoidance {
            get {
                return ResourceManager.GetString("UI_Tooltip_EnableAvoidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, targeting strategies will target FATE mobs as long as the player is inside a FATE area. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_FateFilter {
            get {
                return ResourceManager.GetString("UI_Tooltip_FateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the Heal behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_Heal {
            get {
                return ResourceManager.GetString("UI_Tooltip_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, other components will treat this botbase as one without user input. This will cause combat routines to autonmatically move into the correct positions etc. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_IsAutonomous {
            get {
                return ResourceManager.GetString("UI_Tooltip_IsAutonomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable the combat assist temporarily. Please note that Kombatant will always start paused. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_IsPaused {
            get {
                return ResourceManager.GetString("UI_Tooltip_IsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will take control from the player when certain attacks occur. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_MechanicWarnings {
            get {
                return ResourceManager.GetString("UI_Tooltip_MechanicWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will automatically pause avoidance when engaging a known boss. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_PauseAvoidanceOnBosses {
            get {
                return ResourceManager.GetString("UI_Tooltip_PauseAvoidanceOnBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the PreCombatBuff behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_PreCombatBuff {
            get {
                return ResourceManager.GetString("UI_Tooltip_PreCombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the Pull behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_Pull {
            get {
                return ResourceManager.GetString("UI_Tooltip_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the PullBuff behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_PullBuff {
            get {
                return ResourceManager.GetString("UI_Tooltip_PullBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable the combat routine to execute the Rest behavior. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_Rest {
            get {
                return ResourceManager.GetString("UI_Tooltip_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 As a non-tank, do not engage enemies before your tank. 的本地化字符串。
        /// </summary>
        public static string UI_Tooltip_SmartPull {
            get {
                return ResourceManager.GetString("UI_Tooltip_SmartPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utilities 的本地化字符串。
        /// </summary>
        public static string UI_Utilities {
            get {
                return ResourceManager.GetString("UI_Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use NavGraph 的本地化字符串。
        /// </summary>
        public static string Use_NavGraph {
            get {
                return ResourceManager.GetString("Use NavGraph", resourceCulture);
            }
        }
    }
}
